 
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - poetry install
script:
  - pytest --cov-report term-missing --cov-branch --cov jsomark tests
after_success:
  - codecov